### ISSUE TITLE
Change of colour would be preferable

### ISSUE THREAD

**Issue by etrahretep** [VisualisationExpo/AquaLickX#1]
No matter what colour choose now, it always stays bleu.
Could this be adapted to re regular colors?

**Comment by VisualisationExpo** [comment]
I will then have to make each color in the same - or near same - accent colors as macOS which I think you're referring to?

I think it could be a good idea to add those.. I didn't think of that. For this the only real option is to have 7 or 8 different Aqua.car and DarkAqua.car one for each accent color.

Or I could make a version that doesn't touch the sidebar, menu bar highlights / selected item. That's of course the easiest solution, but then it would not fit my vision of the theme

**Comment by etrahretep** [comment]
"I will then have to make each color in the same - or near same - accent colors as macOS which I think you're referring to?"
Actually yes. If that would imply to load each color when changing color, that would be a pain. They had to switch when selecting a color in preferences.

**Comment by VisualisationExpo** [comment]
I can't edit the selected item color / graphic via accent color only - so yes, it would be a pain to have to load a new `Aqua.car` and `DarkAqua.car` for each accent change. It's something I'm willing to look into, but currently there isn't a different `.car` file that handles accent colors  - - that would be ideal to change. Accent colors is a single color rather than a graphic.
There's the option to tint the accent colors, but that's with a different color and not a graphic like those in the MICA section; `.caar` files
