### ISSUE TITLE
macOS Sonoma Permission Issue

### ISSUE THREAD

**Issue by adambeggs** [VisualisationExpo/AquaLickX#2]
Hello, there is an issue with permissions the it comes to changing the system resources even with SIP and Authenticated-root disabled. Is there a possible work around, or are we at a loss when it comes to updating those specific resources?

**Comment by VisualisationExpo** [comment]
There shouldn't be a problem really. It ought to work the same way - meaning the way you mount your system drive in a folder and replace files that way. Using the commands in the document.

I've done it recently with an update to my BBX Mercury theme for Sonoma*



*the update has to be remade because of an assets error. It might be the same with AquaLickX
